#!/bin/bash
#
# $Id: test.script 203 2015-02-04 08:05:20Z wimalopaan $
#
#  scanbd - KMUX scanner button daemon
#
#  Copyright (C) 2008 - 2015  Wilhelm Meier (wilhelm.meier@fh-kl.de)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
#

# look in scanbd.conf for environment variables

logger -t "scanbd: $0" "Begin of $SCANBD_ACTION for device $SCANBD_DEVICE"

# printout all env-variables
/usr/bin/printenv > `mktemp -t scanbd.script.env.XXXXXXXXXX`

#### CUSTOM ####
now=$(TZ="Europe/Berlin" date +"%Y-%m-%d_%H-%M-%S")
root_path="/mnt/nas/scans/processing"
raw_path="raw/${now}"

# change directory
cd ${root_path}
logger -t "scanbd: $0" "CUSTOM: chdir to ${root_path}"
mkdir ${raw_path}
logger -t "scanbd: $0" "CUSTOM: mkdir ${raw_path}"
cd ${raw_path}
logger -t "scanbd: $0" "CUSTOM: chdir to ${raw_path}"

# scan files to pnm
logger -t "scanbd: $0" "CUSTOM: launching scanimage --source \"ADF Duplex\" --batch=%d.pnm"
scanimage --source "ADF Duplex" --batch=%d.pnm

#scanadf --source "ADF Duplex" -o ${filename}.pnm

logger -t "scanbd: $0" "End   of $SCANBD_ACTION for device $SCANBD_DEVICE"
